create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  invoice_id text not null unique,
  customer_name text not null,
  customer_email text,
  invoice_date date not null,
  due_date date not null,
  amount numeric not null,
  tax numeric not null default 0,
  total numeric not null,
  status text not null,
  payment_method text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_invoices_created_at on public.invoices(created_at desc);
create index if not exists idx_invoices_status on public.invoices(status);

alter table public.invoices enable row level security;

create policy "Authenticated users can read invoices"
  on public.invoices for select
  to authenticated
  using (true);

create policy "Authenticated users can insert invoices"
  on public.invoices for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update invoices"
  on public.invoices for update
  to authenticated
  using (true);

create policy "Authenticated users can delete invoices"
  on public.invoices for delete
  to authenticated
  using (true);
