create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  customer_name text not null,
  customer_phone text,
  order_date date not null,
  shipping_address text,
  items_count int not null default 0,
  subtotal numeric not null,
  shipping_cost numeric not null default 0,
  discount numeric not null default 0,
  total numeric not null,
  status text not null,
  tracking_number text,
  estimated_delivery date,
  created_at timestamptz not null default now()
);

create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_status on public.orders(status);

alter table public.orders enable row level security;

create policy "Authenticated users can read orders"
  on public.orders for select
  to authenticated
  using (true);

create policy "Authenticated users can insert orders"
  on public.orders for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update orders"
  on public.orders for update
  to authenticated
  using (true);

create policy "Authenticated users can delete orders"
  on public.orders for delete
  to authenticated
  using (true);
